pipeline {
    agent {
        docker {  image 'node:16-alpine' }
    stages {
       stage("hello") {
           steps {
               echo "welocme to Jenkins ipeline"
           }
       }
    }
}

